/* Generated by build/generate-cms-artifacts.js. Do not edit directly. */
window.PROJECTS = [
  {
    "id": "smartSentence",
    "title": "Smart Sentence Retriever",
    "subtitle": "NLP Embeddings & Serverless Retrieval",
    "image": "img/projects/smartSentence.png",
    "imageWidth": 952,
    "imageHeight": 952,
    "videoWebm": "img/projects/smartSentence.webm",
    "videoMp4": "img/projects/smartSentence.mp4",
    "tools": [
      "Python",
      "AWS",
      "Docker",
      "NLP"
    ],
    "concepts": [
      "Machine Learning",
      "Automation"
    ],
    "audiences": [
      "data-science"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/Smart-Sentence-Finder",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_13.pdf",
        "label": "PDF"
      },
      {
        "icon": "img/icons/jupyter-icon.png",
        "url": "documents/Project_13.ipynb",
        "label": "Notebook"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/sentence-demo",
        "label": "Live Demo"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.gutenberg.org/ebooks/11",
        "label": "Corpus (Project Gutenberg)",
        "type": "data"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "sentence-demo.html"
    },
    "demoInstructions": {
      "lead": "Search a fixed Alice in Wonderland corpus by meaning, not exact wording.",
      "bullets": [
        "Type a query (a phrase or full sentence).",
        "Adjust “Top results” to control how many matches are returned.",
        "Click “Find Sentences” and review the ranked semantic matches.",
        "If the demo is warming up after idle time, wait for the status to turn ready and try again."
      ]
    },
    "role": [
      "Built the retrieval pipeline, Lambda API, and browser demo end to end."
    ],
    "notes": "The live demo uses a fixed Alice in Wonderland corpus and checks endpoint health before enabling queries because cold starts can happen after idle time.",
    "problem": "I wanted a fast way to retrieve sentences that answer a question even when the wording doesn't match exactly.",
    "actions": [
      "Cleaned Project Gutenberg text, split it into sentences, and precomputed embeddings for the fixed corpus.",
      "Compared several embedding models on a sample subset and balanced clustering quality against model size and serverless deployment cost.",
      "Deployed the selected model behind an immutable AWS Lambda alias and a same-origin IAM proxy, with a browser demo that checks `/health` before ranking top-k matches by cosine similarity."
    ],
    "results": [
      "Shipped a working semantic-search demo for Alice in Wonderland that returns ranked sentence matches instead of keyword hits.",
      "Kept the site embed usable with warm-up status, inline similarity bars, and an open-in-new-tab fallback for a larger view."
    ],
    "personalStory": {
      "why": "I wanted to find sentences by meaning when the query and source use different words.",
      "surprise": "Embedding quality was only one tradeoff; model size, cold starts, and serverless cost mattered to whether the demo felt useful.",
      "next": "I’d publish a repeatable relevance and latency benchmark across the candidate embedding models."
    },
    "evaluation": {
      "status": "not-benchmarked",
      "goal": "Retrieve sentences that are semantically relevant to a query when the wording does not match exactly.",
      "dataset": "A fixed Alice’s Adventures in Wonderland corpus from Project Gutenberg.",
      "split": "The repository includes an exploratory benchmark command over up to 1,000 sentences, but no fixed labeled evaluation split is published.",
      "baseline": "No keyword-search or labeled-relevance baseline is published.",
      "metrics": [],
      "decision": "Selected an embedding model by balancing exploratory clustering behavior, model size, and serverless deployment cost.",
      "limitations": [
        "Comparative relevance, nDCG, recall-at-k, warm latency, and cold-start latency results have not been published.",
        "Silhouette score on unlabeled sentence embeddings would not by itself establish search relevance."
      ],
      "evidence": {
        "label": "Project repository",
        "url": "https://github.com/danielshort3/Smart-Sentence-Finder"
      }
    },
    "order": 1
  },
  {
    "id": "chatbotLora",
    "title": "Chatbot (LoRA + RAG)",
    "subtitle": "RAG Chatbot Fine-Tuned with LoRA",
    "image": "img/projects/chatbotLora.png",
    "imageWidth": 1280,
    "imageHeight": 720,
    "videoWebm": "img/projects/chatbotLora.webm",
    "videoMp4": "img/projects/chatbotLora.mp4",
    "tools": [
      "Python",
      "Ollama",
      "AWS",
      "Docker"
    ],
    "concepts": [
      "Machine Learning",
      "Automation"
    ],
    "audiences": [
      "data-science",
      "tourism"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/Chatbot-LoRA-RAG",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/chatbot-demo",
        "label": "Live Demo"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "chatbot-demo.html",
      "fit": "viewport",
      "minHeight": 620,
      "maxHeight": 860
    },
    "demoInstructions": {
      "lead": "Ask a question and get an answer grounded in the site content (with citations).",
      "bullets": [
        "Click a quick prompt to submit it automatically, or type your own question in the chat box.",
        "Press Enter or click “Send” to submit custom questions.",
        "Use the citations in the response to jump to the referenced pages.",
        "Bedrock is the default live backend; choose Qwen / SageMaker only when comparing cold-start behavior."
      ]
    },
    "role": [
      "Built the prototype from crawl to deployment, then expanded it into a dual-backend demo comparing a custom LoRA/SageMaker model with a live Bedrock model."
    ],
    "notes": "Uses public Visit Grand Junction pages; retrieval provides citation links, and cold-start checks are part of the deployed demo.",
    "problem": "The project needed to show both sides of a tourism chatbot decision: a custom fine-tuned model that could learn destination voice and a production-ready managed model that could answer quickly with citations.",
    "actions": [
      "Crawled Visit Grand Junction pages, built a FAISS retrieval index, and generated a tourism-specific Q&A dataset with an open-source LLM through Ollama.",
      "Fine-tuned a Mistral 7B/Qwen-style chatbot path with LoRA and deployed the custom model behind AWS SageMaker/Lambda for cold-start and model-control comparison.",
      "Added a Bedrock backend as the default live path, keeping the same RAG/citation experience while providing faster always-available responses for the website demo.",
      "Built the web interface, backend selector, health checks, warm-up state, streaming answer handling, and citation rendering so both models can be compared in one demo."
    ],
    "results": [
      "The project now demonstrates both architectures: Bedrock as the practical live production path and LoRA/SageMaker as the custom fine-tuning path.",
      "Viewers can compare managed-model reliability, streaming responses, and citation behavior against the custom model's cold-start and deployment tradeoffs.",
      "The demo keeps source-grounded answers and citation links while making the model choice transparent through the backend selector."
    ],
    "personalStory": {
      "why": "I wanted to compare a custom LoRA deployment with a managed model without giving up grounded answers and citations.",
      "surprise": "The model was only part of the product: cold starts, health checks, streaming, and citation clarity shaped the experience just as much.",
      "next": "I’d publish a controlled benchmark for retrieval hit rate, citation correctness, answer quality, and warm/cold p50 and p95 latency."
    },
    "evaluation": {
      "status": "not-benchmarked",
      "goal": "Compare source-grounded tourism answers across a managed Bedrock backend and a custom LoRA/SageMaker backend.",
      "dataset": "Public Visit Grand Junction pages plus a generated tourism question-and-answer set.",
      "split": "No controlled evaluation split is documented in the published project.",
      "baseline": "No controlled Bedrock-versus-LoRA quality or latency baseline has been published.",
      "metrics": [],
      "decision": "Bedrock remains the default live path; LoRA/SageMaker remains available for architecture and cold-start comparison.",
      "limitations": [
        "Retrieval hit rate, citation correctness, answer quality, and warm/cold p50 and p95 latency have not been published.",
        "The current demo demonstrates the two architectures; it does not establish that one backend produces better answers."
      ],
      "evidence": {
        "label": "Project repository",
        "url": "https://github.com/danielshort3/Chatbot-LoRA-RAG"
      }
    },
    "order": 2
  },
  {
    "id": "shapeClassifier",
    "title": "Shape Classifier Demo",
    "subtitle": "Handwritten Shape Recognition",
    "image": "img/projects/shapeClassifier.png",
    "imageWidth": 926,
    "imageHeight": 926,
    "videoWebm": "img/projects/shapeClassifier.webm",
    "videoMp4": "img/projects/shapeClassifier.mp4",
    "tools": [
      "Python",
      "PyTorch",
      "AWS",
      "Docker"
    ],
    "concepts": [
      "Machine Learning"
    ],
    "audiences": [
      "data-science"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/Shape-Analyzer",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://github.com/googlecreativelab/quickdraw-dataset",
        "label": "Quick, Draw! Dataset",
        "type": "data"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/shape-demo",
        "label": "Live Demo"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "shape-demo.html"
    },
    "demoInstructions": {
      "lead": "Draw one of the supported shapes and let the model classify it.",
      "bullets": [
        "Draw on the canvas (circle, triangle, square, hexagon, or octagon).",
        "Click “Classify” to submit the drawing.",
        "Use the eraser button (or press C) to clear and try again.",
        "Review the confidence bar and per-shape scores on the right."
      ]
    },
    "problem": "I wanted a model that can tell what shape someone drew.",
    "actions": [
      "Used Google's QuickDraw sketches and built train/validation splits.",
      "Trained a small ResNet18 classifier in PyTorch.",
      "Deployed a CPU-only AWS Lambda endpoint so the browser can request predictions."
    ],
    "results": [
      "Supports five QuickDraw classes—circle, triangle, square, hexagon, and octagon—but a held-out accuracy result has not yet been published.",
      "Predictions return quickly once the Lambda container is warm; cold starts can take longer."
    ],
    "evaluation": {
      "status": "not-benchmarked",
      "goal": "Classify a browser-drawn shape as one of five supported QuickDraw classes.",
      "dataset": "Google Quick, Draw! sketches for circle, triangle, square, hexagon, and octagon.",
      "split": "Train and validation splits were created, but their sizes and sampling procedure are not published.",
      "baseline": "No simple classifier or majority-class baseline is published.",
      "metrics": [],
      "decision": "Deployed the ResNet18 classifier for CPU-only serverless inference in the live demonstration.",
      "limitations": [
        "Held-out accuracy, per-class recall, and confusion-matrix results have not been published.",
        "QuickDraw sketches may not represent drawings made with the website’s canvas and preprocessing pipeline."
      ],
      "evidence": {
        "label": "Project repository",
        "url": "https://github.com/danielshort3/Shape-Analyzer"
      }
    },
    "order": 3,
    "notes": "The live demo runs CPU-only serverless inference on five QuickDraw shape classes, so confidence is scoped to that small drawing task."
  },
  {
    "id": "ufoDashboard",
    "title": "UFO Sightings Dashboard",
    "subtitle": "Tableau Geospatial Analytics",
    "image": "img/projects/ufoDashboard.png",
    "imageWidth": 2008,
    "imageHeight": 1116,
    "tools": [
      "Tableau"
    ],
    "concepts": [
      "Visualization",
      "Analytics"
    ],
    "audiences": [
      "analytics"
    ],
    "resources": [
      {
        "icon": "img/icons/tableau-icon.png",
        "url": "https://public.tableau.com/views/UFO_Sightings_16769494135040/UFOSightingDashboard-2013?:language=en-US&:display_count=n&:origin=viz_share_link",
        "label": "Interactive Dashboard"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://nuforc.org/databank/",
        "label": "NUFORC Database",
        "type": "data"
      }
    ],
    "embed": {
      "type": "tableau",
      "base": "https://public.tableau.com/views/UFO_Sightings_16769494135040/UFOSightingDashboard-2013"
    },
    "demoInstructions": {
      "lead": "Use the interactive Tableau dashboard to explore sightings by place, time, and shape.",
      "bullets": [
        "Hover charts/maps for tooltips and quick readouts.",
        "Click marks (states/cities/shapes) to filter and cross-highlight views.",
        "Use Tableau controls to refine the slice you’re looking at.",
        "Scroll to compare time-of-day and seasonality patterns across views."
      ]
    },
    "problem": "I wanted to see patterns in UFO sighting reports across the U.S.",
    "actions": [
      "Cleaned and standardized a public UFO sightings dataset.",
      "Built a Tableau dashboard with maps and time-based charts."
    ],
    "results": [
      "In this dataset, reports are most common in the evening/night hours (and shift seasonally with daylight).",
      "California has the most reports in the dataset, while many central states have fewer."
    ],
    "order": 4,
    "notes": "The dashboard uses reported UFO sightings without population normalization, so patterns should be read as report volume, not incidence rates."
  },
  {
    "id": "covidAnalysis",
    "title": "COVID-19 Outbreak Drivers",
    "subtitle": "Python XGBoost & SHAP",
    "image": "img/projects/covidAnalysis.png",
    "imageWidth": 1446,
    "imageHeight": 1446,
    "videoWebm": "img/projects/covidAnalysis.webm",
    "videoMp4": "img/projects/covidAnalysis.mp4",
    "tools": [
      "Python",
      "AWS"
    ],
    "concepts": [
      "Analytics"
    ],
    "audiences": [
      "analytics",
      "tourism"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/Covid-Analysis",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/covid-outbreak-demo",
        "label": "Live Demo"
      },
      {
        "icon": "img/icons/jupyter-icon.png",
        "url": "https://github.com/danielshort3/Covid-Analysis/blob/main/covid_analysis.ipynb",
        "label": "Current Notebook (GitHub)"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://healthdata.gov/Hospital/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/anag-cw7u",
        "label": "HHS Dataset",
        "type": "data"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "covid-outbreak-demo.html"
    },
    "demoInstructions": {
      "lead": "Explore how ICU breach risk changes over time, and what’s driving it.",
      "bullets": [
        "Wait for the status pill to show the demo is ready (cold starts can take a moment).",
        "Drag the date slider to move through time.",
        "Hover or click a state to see its risk score, top drivers, and recent trend.",
        "Use the hotspots list to quickly jump to the highest-risk locations."
      ]
    },
    "problem": "Using 2020-2023 HHS hospital-capacity data, I built an early-warning model to flag states at risk of crossing 90% ICU utilization in the next 7 days.",
    "actions": [
      "Cleaned and enriched 50k+ rows from the HHS hospital-capacity time series; added rolling stats, trends, and 1/3/7/14-day lag features.",
      "Trained an XGBoost classifier with class-imbalance weighting and a strict time-based train/test split."
    ],
    "results": [
      "Used SHAP to highlight the top drivers and embedded an interactive plot in the report.",
      "Top driver was the share of ICU beds occupied by COVID patients.",
      "Exported daily, per-state risk scores (probability of breaching 90% ICU utilization within 7 days)."
    ],
    "evaluation": {
      "status": "measured",
      "goal": "Flag states at risk of exceeding 90% ICU utilization within the next seven days.",
      "dataset": "56,853 state-date rows derived from the HHS hospital-capacity time series.",
      "split": "38,217 rows before 2022-07-01 for training and 18,636 rows from 2022-07-01 onward for time-based evaluation.",
      "baseline": "No-skill AUROC is 0.500; approximately 4.1% positive prevalence in the evaluation period implies a PR-AUC baseline of about 0.041.",
      "metrics": [
        {
          "label": "AUROC",
          "value": "0.606",
          "context": "Time-based evaluation period."
        },
        {
          "label": "PR-AUC",
          "value": "0.060",
          "context": "Compared with an approximate prevalence baseline of 0.041."
        },
        {
          "label": "Recall at 75% precision",
          "value": "0.000",
          "context": "The model did not identify positives at the stated precision target."
        },
        {
          "label": "Confusion matrix at 0.5",
          "value": "31 TP / 728 FN",
          "context": "17,601 true negatives and 276 false positives."
        }
      ],
      "decision": "Treat the output as an exploratory risk-scoring demonstration, not an operational alerting model; performance does not support use at a 75% precision target.",
      "limitations": [
        "The post-cutoff evaluation data was also passed to XGBoost for early stopping, so it is not an untouched final holdout.",
        "The target is highly imbalanced and aggregated at the state level; the model is not a clinical forecast."
      ],
      "evidence": {
        "label": "Current XGBoost notebook",
        "url": "https://github.com/danielshort3/Covid-Analysis/blob/main/covid_analysis.ipynb"
      }
    },
    "order": 5,
    "notes": "The model is a 7-day state-level ICU breach risk scorer based on HHS hospital-capacity data, not a clinical forecast."
  },
  {
    "id": "targetEmptyPackage",
    "title": "Empty-Package Shrink Dashboard",
    "subtitle": "Excel Forecasting & BI",
    "image": "img/projects/targetEmptyPackage.png",
    "imageWidth": 1460,
    "imageHeight": 1460,
    "videoWebm": "img/projects/targetEmptyPackage.webm",
    "videoMp4": "img/projects/targetEmptyPackage.mp4",
    "tools": [
      "Excel",
      "Time-Series",
      "AWS"
    ],
    "concepts": [
      "Automation",
      "Analytics"
    ],
    "audiences": [
      "analytics"
    ],
    "resources": [
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_7.pdf",
        "label": "PDF"
      },
      {
        "icon": "img/icons/excel-icon.png",
        "url": "documents/Project_7.xlsx",
        "label": "Excel"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/target-empty-package-demo",
        "label": "Live Demo"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "target-empty-package-demo.html"
    },
    "demoInstructions": {
      "lead": "Explore shrink trends and hotspots with filters and breakdown tabs.",
      "bullets": [
        "Wait for the dashboard to finish warming up and load data.",
        "Switch between “Retail Value” and “Incident Count” depending on what you want to compare.",
        "Apply filters (location, condition, department, associate, date range) to narrow the view.",
        "Use “Reset filters” to quickly return to the full dataset."
      ]
    },
    "role": [
      "Built the Excel dashboard workflow (cleanup, drill-downs, and reporting)."
    ],
    "notes": "Employee and location identifiers are anonymized; the dashboard compares both incident count and retail value so hotspots are not judged by volume alone.",
    "problem": "Empty-package shrink was growing, and leaders needed a single view of trends, hotspots, and forecasted risk across locations and departments.",
    "actions": [
      "Cleaned and anonymized 2021-2023 loss-prevention records into a dashboard-ready dataset.",
      "Built Excel drill-downs for location, department, associate, recovery location, date range, incident count, and retail value.",
      "Added trend and forecasting views so stakeholders could spot acceleration, not just historical totals."
    ],
    "results": [
      "Identified a small set of locations, departments, and recovery paths driving disproportionate shrink.",
      "Made growth periods and hotspots visible enough for targeted review instead of broad manual scanning.",
      "Created a reusable BI workflow that can be refreshed and extended with anomaly alerts."
    ],
    "order": 6
  },
  {
    "id": "handwritingRating",
    "title": "Handwriting Legibility Scoring",
    "subtitle": "PyTorch CNN Fine-Tuning",
    "image": "img/projects/handwritingRating.png",
    "imageWidth": 1138,
    "imageHeight": 1138,
    "videoWebm": "img/projects/handwritingRating.webm",
    "videoMp4": "img/projects/handwritingRating.mp4",
    "videoOnly": true,
    "tools": [
      "Python",
      "PyTorch",
      "AWS",
      "Docker",
      "CNN"
    ],
    "concepts": [
      "Machine Learning"
    ],
    "audiences": [
      "data-science"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/Handwriting-Rating",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/handwriting-rating-demo",
        "label": "Live Demo"
      },
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_8.pdf",
        "label": "PDF"
      },
      {
        "icon": "img/icons/jupyter-icon.png",
        "url": "documents/Project_8.ipynb",
        "label": "Notebook"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.tensorflow.org/datasets/catalog/mnist",
        "label": "MNIST Dataset",
        "type": "data"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "handwriting-rating-demo.html"
    },
    "demoInstructions": {
      "lead": "Draw a digit (0-9) or load a sample, then score how legible it is.",
      "bullets": [
        "Pick a sample from “Daniel’s Handwritten Numbers”, or draw a digit on the canvas.",
        "Click “Rate digit” to submit.",
        "Use the eraser to clear the canvas and try another digit.",
        "Review the predicted digit, confidence, and legibility score breakdown."
      ]
    },
    "problem": "My wife says my handwriting is hard to read. I wanted an objective score.",
    "actions": [
      "Built three digit-recognition models, moving from a simple baseline to a CNN.",
      "Trained on MNIST (60,000 digits) and selected the best model.",
      "Deployed it behind a serverless scoring API for the live demo."
    ],
    "results": [
      "The best model reached ~99% test accuracy on MNIST (see notebook).",
      "On a small personal handwriting set, accuracy was ~75.6% (not a benchmark; see notebook).",
      "My wife was right."
    ],
    "evaluation": {
      "status": "measured",
      "goal": "Recognize handwritten digits and use model confidence as one input to a legibility score.",
      "dataset": "MNIST plus a small personal handwriting set used only as a domain-shift check.",
      "split": "Standard MNIST training and test datasets: 60,000 training digits and 10,000 test digits.",
      "baseline": "The first model reached 92.302% accuracy on the MNIST test set.",
      "metrics": [
        {
          "label": "Best MNIST test accuracy",
          "value": "98.952%",
          "context": "Model v3, selected from the three notebook architectures."
        },
        {
          "label": "Personal handwriting accuracy",
          "value": "75.56%",
          "context": "Small custom set; included as a domain-shift check, not a benchmark."
        }
      ],
      "decision": "Selected model v3 because it produced the highest recorded MNIST test accuracy.",
      "limitations": [
        "MNIST is a narrow digit-recognition dataset and does not represent general handwriting legibility.",
        "The custom handwriting sample is small and its size is not documented in the published result."
      ],
      "evidence": {
        "label": "Evaluation notebook",
        "url": "documents/Project_8.ipynb"
      }
    },
    "order": 7,
    "notes": "MNIST is the training baseline; the personal handwriting scores are a domain-shift check, not a full handwriting benchmark."
  },
  {
    "id": "digitGenerator",
    "title": "Synthetic Digit Generator",
    "subtitle": "Variational Autoencoder",
    "image": "img/projects/digitGenerator.png",
    "imageWidth": 1470,
    "imageHeight": 1470,
    "videoWebm": "img/projects/digitGenerator.webm",
    "videoMp4": "img/projects/digitGenerator.mp4",
    "tools": [
      "Python",
      "VAE",
      "AWS",
      "Docker"
    ],
    "concepts": [
      "Machine Learning"
    ],
    "audiences": [
      "data-science"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/Handwritten-Digit-Generator",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/digit-generator-demo",
        "label": "Live Demo"
      },
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_9.pdf",
        "label": "PDF"
      },
      {
        "icon": "img/icons/jupyter-icon.png",
        "url": "documents/Project_9.ipynb",
        "label": "Notebook"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "/digit-generator-demo"
    },
    "demoInstructions": {
      "lead": "Generate a grid of synthetic digits and explore how the output morphs.",
      "bullets": [
        "Use the blue “Number” control to choose Auto or a digit from 0–9.",
        "Click “Generate” to refresh the grid.",
        "Open “Extra settings” to adjust seed, dim, grid density, minimum grid height, and distortion level.",
        "Generate again to compare how settings change the outputs."
      ]
    },
    "problem": "I wanted to generate new handwritten digits, not just recognize them.",
    "actions": [
      "Trained a Variational Autoencoder (VAE) on MNIST (60,000 training digits) with a 20-dim latent space for up to 100 epochs."
    ],
    "results": [
      "Generated new digits by sampling the learned latent space.",
      "Saved the trained model so generation is a quick inference step."
    ],
    "personalStory": {
      "why": "I wanted to generate new handwritten digits instead of only recognizing them.",
      "surprise": "A smooth latent space made generation fast, but MNIST’s narrow style limits how representative the samples are of real handwriting.",
      "next": "I’d compare latent sizes and add explicit fidelity and diversity evaluation before calling one model better."
    },
    "evaluation": {
      "status": "partial",
      "goal": "Generate plausible MNIST-style digits by sampling a learned variational latent space.",
      "dataset": "MNIST: 60,000 training digits and 10,000 test digits.",
      "split": "The standard MNIST train and test datasets were used; the test loss also selected the saved checkpoint.",
      "baseline": "Epoch 1 test loss was 107.9880 using the notebook’s binary-cross-entropy plus KL-divergence objective.",
      "metrics": [
        {
          "label": "Best test loss",
          "value": "93.5655",
          "context": "Lowest recorded BCE + KL loss across the 100-epoch notebook run."
        }
      ],
      "decision": "Saved the checkpoint with the lowest recorded test loss for the interactive generator.",
      "limitations": [
        "The test set was used for checkpoint selection, so it is not an untouched final holdout.",
        "No FID-style, classifier-based, diversity, or human-quality benchmark is published; generated samples remain a qualitative result."
      ],
      "evidence": {
        "label": "Training notebook",
        "url": "documents/Project_9.ipynb"
      }
    },
    "order": 8,
    "notes": "Trained on MNIST; generated samples reflect that digit domain rather than real handwriting diversity."
  },
  {
    "id": "sheetMusicUpscale",
    "title": "Sheet Music Watermark Removal & Upscale",
    "subtitle": "UNet & VDSR Pipeline",
    "image": "img/projects/sheetMusicUpscale.png",
    "imageWidth": 1604,
    "imageHeight": 1230,
    "videoWebm": "img/projects/sheetMusicUpscale.webm",
    "videoMp4": "img/projects/sheetMusicUpscale.mp4",
    "tools": [
      "Python",
      "Computer Vision"
    ],
    "concepts": [
      "Machine Learning"
    ],
    "audiences": [
      "data-science"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/Watermark-Remover",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_10_pdf.zip",
        "label": "PDFs"
      },
      {
        "icon": "img/icons/jupyter-icon.png",
        "url": "documents/Project_10.zip",
        "label": "Notebook"
      }
    ],
    "problem": "I needed clean, readable sheet music. Most of what I could find was low-res and watermarked.",
    "actions": [
      "Trained a UNet model on paired page images for watermark removal.",
      "Upscaled low-resolution scans (e.g., ~612x792) to print-friendly resolution (e.g., ~1700x2200) with Very Deep Super-Resolution (VDSR).",
      "Wrapped it in a simple GUI so I could run the full pipeline."
    ],
    "results": [
      "Typical runs produce cleaner, more readable output in seconds per page (hardware- and batch-dependent)."
    ],
    "evaluation": {
      "status": "partial",
      "goal": "Remove visible watermarks and upscale low-resolution sheet-music pages while preserving readable notation.",
      "dataset": "Paired page images used to train the watermark-removal model.",
      "split": "Dataset size and train, validation, and test partitions are not documented in the published project.",
      "baseline": "No interpolation-only or image-restoration baseline is published.",
      "metrics": [],
      "decision": "Combined a UNet watermark-removal stage with VDSR upscaling in the desktop workflow.",
      "limitations": [
        "No held-out image-quality, OCR, staff-line preservation, or reader study result is published.",
        "Runtime and output quality vary with hardware, batch size, source resolution, and scan quality."
      ],
      "evidence": {
        "label": "Project repository",
        "url": "https://github.com/danielshort3/Watermark-Remover"
      }
    },
    "order": 9,
    "notes": "Designed for low-resolution, watermarked page images; output quality depends on scan quality and staff-line preservation."
  },
  {
    "id": "deliveryTip",
    "title": "Delivery Tip",
    "subtitle": "Excel Geo-Analytics & Optimization",
    "image": "img/projects/deliveryTip.png",
    "imageWidth": 960,
    "imageHeight": 794,
    "tools": [
      "Excel",
      "Power Query"
    ],
    "concepts": [
      "Analytics"
    ],
    "audiences": [
      "analytics"
    ],
    "resources": [
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_11.pdf",
        "label": "PDF"
      },
      {
        "icon": "img/icons/excel-icon.png",
        "url": "documents/Project_11.xlsx",
        "label": "Excel"
      }
    ],
    "problem": "I wanted to know which shifts and neighborhoods lead to better tips.",
    "actions": [
      "Built a geospatial heat map and pivot filters from 1,251 deliveries.",
      "Compared tips by daypart, zone, and order size."
    ],
    "results": [
      "Mid-week shifts tended to have higher tips per delivery, while Friday evenings tended to have higher tips per hour.",
      "Neighborhood and housing type differences explained a lot of the variation in this dataset.",
      "Used the dashboard to make better shift and zone choices over time."
    ],
    "order": 10,
    "notes": "The Excel workflow is built from personal delivery-ticket history, so the findings are useful for shift planning but not intended as a universal tipping model."
  },
  {
    "id": "retailStore",
    "title": "Store-Level Loss & Sales ETL",
    "subtitle": "SQL ETL + Anomaly Detection",
    "image": "img/projects/retailStore.png",
    "imageWidth": 1410,
    "imageHeight": 1410,
    "videoWebm": "img/projects/retailStore.webm",
    "videoMp4": "img/projects/retailStore.mp4",
    "tools": [
      "SQL",
      "Python",
      "AWS"
    ],
    "concepts": [
      "Automation",
      "Analytics"
    ],
    "audiences": [
      "analytics",
      "tourism"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/target-packaging-analysis-mssql",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_12.pdf",
        "label": "PDF"
      },
      {
        "icon": "img/icons/jupyter-icon.png",
        "url": "documents/Project_12.ipynb",
        "label": "Notebook"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/retail-loss-sales-demo",
        "label": "Live Demo"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "retail-loss-sales-demo.html"
    },
    "demoInstructions": {
      "lead": "Compare store-level incident signals against sales metrics using tabs and filters.",
      "bullets": [
        "Pick a region to filter incidents and trends.",
        "Switch sales metrics (Total, Online, Drive-up) to change the sales view.",
        "Switch incident metrics (Count vs. Proven $) to change the incident view.",
        "Use “Reset view” to return to the default slice."
      ]
    },
    "role": [
      "Led the analysis: SQL modeling/ETL, anomaly detection, and reporting."
    ],
    "notes": "Store, state, and employee identifiers are anonymized; risk rankings normalize incident signals with sales context so high-volume stores are not treated as high-risk by volume alone.",
    "problem": "Leaders needed one reliable way to compare security incidents, theft hotspots, and sales signals without stitching together separate reports.",
    "actions": [
      "Modeled incident, sales, and HR data in SQL so stores, regions, time periods, and risk measures use consistent definitions.",
      "Built Python reporting views that separate frequency, severity, and sales context for faster investigation planning.",
      "Used anomaly detection to flag outlier stores, regions, and associate patterns for review."
    ],
    "results": [
      "Supported analytics-driven investigations that reduced inventory loss by 24%.",
      "Improved theft reporting by 57.6% through clearer dashboards and workflow redesign.",
      "Narrowed broad incident data into a short, explainable list of hotspots worth investigating.",
      "Kept identifiers anonymized so the case study can show the workflow without exposing people or locations."
    ],
    "personalStory": {
      "why": "I wanted to turn scattered incident and sales data into a short, explainable list of stores worth investigating.",
      "surprise": "Raw incident volume was misleading; sales context and normalization changed which stores looked genuinely unusual.",
      "next": "I’d calibrate alert thresholds against reviewed cases and add drift monitoring so the ranking stays useful over time."
    },
    "order": 11
  },
  {
    "id": "pizza",
    "title": "Pizza Tips Regression Modeling",
    "subtitle": "Excel Analytics & Regression Modeling",
    "image": "img/projects/pizza.png",
    "imageWidth": 1398,
    "imageHeight": 1398,
    "videoWebm": "img/projects/pizza.webm",
    "videoMp4": "img/projects/pizza.mp4",
    "tools": [
      "Excel",
      "Statistics",
      "AWS"
    ],
    "concepts": [
      "Analytics"
    ],
    "audiences": [
      "analytics"
    ],
    "resources": [
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/pizza-tips-demo",
        "label": "Live Demo"
      },
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_1.pdf",
        "label": "PDF"
      },
      {
        "icon": "img/icons/excel-icon.png",
        "url": "documents/Project_1.xlsx",
        "label": "Excel"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "pizza-tips-demo.html"
    },
    "demoInstructions": {
      "lead": "Adjust inputs and estimate a tip using the regression model.",
      "bullets": [
        "Use the delivery slider to load an example ticket (or enter values directly).",
        "Edit order cost and other inputs (housing, time, weather) to test scenarios.",
        "Click “Estimate Tip” to see the prediction.",
        "Use “Reset” to return to defaults."
      ]
    },
    "problem": "Tips varied a lot by neighborhood and housing type. I wanted to see what actually drives them.",
    "actions": [
      "Merged 1,251 delivery tickets with NOAA weather, then cleaned the data in Power Query.",
      "Ran a multiple regression in Excel: Tip = f(cost, delivery time, rain, max/min temperature)."
    ],
    "results": [
      "Order cost was the strongest predictor of tip size in the regression.",
      "Housing type (apartment vs. house) showed a statistically significant difference in this sample.",
      "Weather and delivery time didn’t show a meaningful effect on tip size."
    ],
    "order": 12,
    "notes": "Delivery records were joined to NOAA daily weather; missing distance and time-of-day controls limit causal interpretation."
  },
  {
    "id": "babynames",
    "title": "Baby Name Predictor",
    "subtitle": "Python ML Pipeline",
    "image": "img/projects/babynames.png",
    "imageWidth": 1238,
    "imageHeight": 1238,
    "videoWebm": "img/projects/babynames.webm",
    "videoMp4": "img/projects/babynames.mp4",
    "tools": [
      "Python",
      "scikit-learn"
    ],
    "concepts": [
      "Machine Learning"
    ],
    "audiences": [
      "analytics"
    ],
    "resources": [
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/baby-names-demo",
        "label": "Live Demo"
      },
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/Baby-Names",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_2.pdf",
        "label": "PDFs"
      },
      {
        "icon": "img/icons/jupyter-icon.png",
        "url": "documents/Project_2.ipynb",
        "label": "Notebook"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.ssa.gov/oact/babynames/",
        "label": "SSA Baby Names Data",
        "type": "data"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "baby-names-demo.html"
    },
    "demoInstructions": {
      "lead": "Explore rated names and similarity-based recommendations.",
      "bullets": [
        "Choose Girls, Boys, or All at the top to change the dataset slice.",
        "In “Ratings Snapshot”, click a rating bar to see the names at that score.",
        "In “Name Explorer”, switch between Recommendations and Rated Names.",
        "Use search + sort to find names quickly."
      ]
    },
    "problem": "My wife asked me to suggest baby names. I wanted something that learns her taste instead of guessing.",
    "actions": [
      "Aggregated SSA baby-name records (1880-present) and engineered trend features.",
      "Built a simple 'quiz' script to collect like/dislike labels.",
      "Trained several models and averaged their scores to produce recommendations."
    ],
    "results": [
      "Generated personalized top 50 name lists for boys and girls.",
      "Helped us narrow the list when naming our child."
    ],
    "order": 13,
    "notes": "Uses SSA baby-name data plus personal quiz labels; recommendations are preference predictions, not a population forecast."
  },
  {
    "id": "pizzaDashboard",
    "title": "Pizza Delivery Dashboard",
    "subtitle": "Tableau Analytics & Forecasting",
    "image": "img/projects/pizzaDashboard.png",
    "imageWidth": 1250,
    "imageHeight": 1092,
    "tools": [
      "Tableau"
    ],
    "concepts": [
      "Visualization",
      "Analytics"
    ],
    "audiences": [
      "analytics",
      "tourism"
    ],
    "resources": [
      {
        "icon": "img/icons/tableau-icon.png",
        "url": "https://public.tableau.com/views/Pizza_Delivery/PizzaDeliveryDashboard?:language=en-US&:display_count=n&:origin=viz_share_link",
        "label": "Interactive Dashboard"
      }
    ],
    "embed": {
      "type": "tableau",
      "base": "https://public.tableau.com/views/Pizza_Delivery/PizzaDeliveryDashboard"
    },
    "demoInstructions": {
      "lead": "Use the Tableau dashboard to compare delivery zones, tips, and timing.",
      "bullets": [
        "Hover charts/maps to see exact values for the current filter state.",
        "Click marks to cross-filter other views and isolate a zone or time period.",
        "Use Tableau filters to narrow by date, city/zone, and other dimensions.",
        "Scroll to review distributions and the forecast section."
      ]
    },
    "role": [
      "Built the dataset and Tableau dashboard (data shaping, KPIs, and forecasting)."
    ],
    "problem": "I needed a Tableau dashboard that could compare delivery zones, earnings, timing, and tip patterns quickly enough to support shift decisions.",
    "actions": [
      "Reshaped about 12,000 delivery records into a Tableau-ready dataset with consistent dates, zones, housing categories, and tip KPIs.",
      "Built map, distribution, filter, and 12-month forecast views for fast zone and timing comparison.",
      "Designed the dashboard around decisions: where to work, what patterns explain tips, and how demand might change."
    ],
    "results": [
      "Reduced delivery decision review from roughly five minutes to about one minute during planning.",
      "Made zone, city, housing-type, tip-rate, and timing differences easier to compare in one view.",
      "Added forecasting so the dashboard supports planning instead of only retrospective review."
    ],
    "order": 14,
    "notes": "Built from delivery history; tip efficiency should be interpreted with zone and timing context rather than average tip alone."
  },
  {
    "id": "nonogram",
    "title": "Nonogram Solver",
    "subtitle": "Reinforcement Learning (RL)",
    "image": "img/projects/nonogram.png",
    "imageWidth": 1228,
    "imageHeight": 1228,
    "videoWebm": "img/projects/nonogram.webm",
    "videoMp4": "img/projects/nonogram.mp4",
    "tools": [
      "Python",
      "PyTorch",
      "AWS",
      "Docker"
    ],
    "concepts": [
      "Machine Learning"
    ],
    "audiences": [
      "data-science"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/Nonogram-Solver",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/nonogram-demo",
        "label": "Live Demo"
      },
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Project_4.pdf",
        "label": "PDF"
      },
      {
        "icon": "img/icons/jupyter-icon.png",
        "url": "documents/Project_4.ipynb",
        "label": "Notebook"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "nonogram-demo.html"
    },
    "demoInstructions": {
      "lead": "Generate a new Nonogram puzzle, then watch the agent solve it step-by-step.",
      "bullets": [
        "Click “New Puzzle” to generate a board.",
        "Once it’s ready, the button switches to “Solve With AI”. Click it to start solving.",
        "Use “Solution” to reveal the full answer key if you want to compare.",
        "If AWS is warming up, wait for the status to turn ready and try again."
      ]
    },
    "problem": "I wanted to see if an RL agent could learn to solve Nonogram puzzles.",
    "actions": [
      "Generated large batches of 5x5 puzzles and trained a hybrid CNN + Transformer policy network to solve them.",
      "Shaped rewards around unique guesses, row/column completions, and full-board solves to guide exploration."
    ],
    "results": [
      "Evaluated on generated 5x5 boards, but the published materials do not yet include a reproducible held-out solve-rate result."
    ],
    "evaluation": {
      "status": "not-benchmarked",
      "goal": "Measure whether the learned policy can complete unseen generated 5x5 Nonogram boards.",
      "dataset": "Generated 5x5 Nonogram puzzles.",
      "split": "The project references held-out boards, but split sizes, seeds, and a reproducible evaluation set are not published.",
      "baseline": "No rule-based, search-based, or random-policy baseline is published.",
      "metrics": [],
      "decision": "Retained the hybrid CNN and Transformer policy for the live step-by-step solver demonstration.",
      "limitations": [
        "A held-out solve rate with board count, seed, and confidence interval has not been published.",
        "Results on generated 5x5 boards do not establish performance on larger or human-authored puzzles."
      ],
      "evidence": {
        "label": "Project repository",
        "url": "https://github.com/danielshort3/Nonogram-Solver"
      }
    },
    "order": 15,
    "notes": "The solver focuses on generated 5x5 puzzles; scaling to larger puzzles would need curriculum learning or search."
  },
  {
    "id": "minesweeper",
    "published": false,
    "title": "Minesweeper Solver",
    "subtitle": "Reinforcement Learning (RL)",
    "image": "img/projects/minesweeper.png",
    "imageWidth": 1280,
    "imageHeight": 720,
    "tools": [
      "Python",
      "PyTorch",
      "AWS",
      "Docker"
    ],
    "concepts": [
      "Machine Learning",
      "Automation"
    ],
    "resources": [
      {
        "icon": "img/icons/website-icon.png",
        "url": "https://www.danielshort.me/minesweeper-demo.html",
        "label": "Live Demo"
      },
      {
        "icon": "img/icons/pdf-icon.png",
        "url": "documents/Minesweeper_Reinforcement_Learning_Web_Application.pdf",
        "label": "PDF"
      }
    ],
    "embed": {
      "type": "iframe",
      "url": "minesweeper-demo.html"
    },
    "demoInstructions": {
      "lead": "Generate a Minesweeper board, then watch the agent solve it move-by-move.",
      "bullets": [
        "Click “New Puzzle” to generate a board.",
        "Once it’s ready, the button switches to “Solve With AI”. Click it to run the solver.",
        "Use “Solution” to reveal the mine layout if you want to compare.",
        "If the backend is warming up, give it a moment and try again."
      ]
    },
    "problem": "I wanted to train an RL agent to play Minesweeper and ship it as a web demo.",
    "actions": [
      "Built a Minesweeper environment that generates boards on demand (5x5 to 10x10), with safe first-click logic and 10-20% mines.",
      "Trained 12 variants across DQN, Double DQN, and Dueling DQN with different CNN heads and replay buffers.",
      "Deployed the best model behind an AWS Lambda container endpoint for interactive inference."
    ],
    "results": [
      "Best evaluation reached ~72% success on 9x9 boards with 10 mines.",
      "The demo uses the 9x9 / 10-mine model for interactive inference."
    ],
    "order": 16,
    "notes": "Training boards are generated on the fly with randomized mine density and a protected first click, so results depend on that environment setup."
  },
  {
    "id": "website",
    "title": "danielshort.me",
    "subtitle": "Responsive Portfolio Site",
    "image": "img/projects/website.png",
    "imageWidth": 1464,
    "imageHeight": 1464,
    "videoWebm": "img/projects/website.webm",
    "videoMp4": "img/projects/website.mp4",
    "tools": [
      "HTML",
      "CSS",
      "JavaScript"
    ],
    "concepts": [
      "Product",
      "Visualization"
    ],
    "audiences": [
      "analytics"
    ],
    "resources": [
      {
        "icon": "img/icons/github-icon.png",
        "url": "https://github.com/danielshort3/danielshort3.github.io",
        "label": "GitHub"
      },
      {
        "icon": "img/icons/website-icon.png",
        "url": "/",
        "label": "Live Site"
      }
    ],
    "problem": "I needed a fast site to show my work, especially on mobile.",
    "actions": [
      "Built a static site and rendered portfolio projects from a single data file.",
      "Added Google Analytics 4, structured data, and lazy loading for heavy assets."
    ],
    "results": [
      "Optimized for fast, mobile-friendly pages with a hashed CSS bundle, lazy-loaded media, and minimal JavaScript.",
      "Makes projects easy to share with clean URLs, social previews, and a searchable portfolio."
    ],
    "personalStory": {
      "why": "I wanted one fast, mobile-friendly place where projects, tools, games, and professional work were easy to understand and share.",
      "surprise": "Keeping content, generated pages, clean routes, and deployment output synchronized became as important as the visual design.",
      "next": "I’d add automated accessibility, broken-link, and Core Web Vitals regression checks to catch quality drift before deployment."
    },
    "order": 17,
    "notes": "Project pages are generated from structured content with canonical metadata and sitemap updates, so portfolio changes stay consistent across the site."
  }
];

window.FEATURED_IDS = [
  "retailStore",
  "targetEmptyPackage",
  "pizzaDashboard",
  "deliveryTip",
  "ufoDashboard"
];
