'use strict';

const assert = require('node:assert/strict');
const { create } = require('../../js/tools/ocean-wave-timer');
let now = 1000;
let complete = 0;
let sequence = 0;
const pending = new Map();
const states = [];
const timer = create({ now: () => now, onTick: state => states.push(state), onComplete: () => complete++,
  schedule: fn => { const id = ++sequence; pending.set(id, fn); return id; }, cancelSchedule: id => pending.delete(id) });
timer.start(15);
assert.equal(states.at(-1).remainingMs, 900000);
assert.equal(states.at(-1).fade, 0);
now += 870000;
timer.refresh();
assert.equal(states.at(-1).fade, 0.5, 'The final minute must fade progressively.');
assert.equal(pending.size, 1, 'Refreshing replaces the timer rather than multiplying callbacks.');
now += 30000;
timer.refresh();
assert.equal(complete, 1);
assert.equal(states.at(-1).fade, 1);
assert.equal(pending.size, 0);
timer.refresh();
assert.equal(complete, 1, 'A finished session must complete only once.');
timer.cancel();
assert.equal(states.at(-1).fade, 0);
timer.start(30);
now += 3600000;
timer.refresh();
assert.equal(complete, 2, 'Returning from a throttled tab must honor the original deadline.');
timer.start(60);
timer.cancel();
now += 3600000;
timer.refresh();
assert.equal(complete, 2, 'Cancelling must prevent later completion.');
timer.start(-1);
assert.equal(pending.size, 0);
timer.start(15);
timer.dispose();
const ticks = states.length;
timer.start(30);
timer.refresh();
timer.cancel();
assert.equal(pending.size, 0);
assert.equal(states.length, ticks, 'Disposed timers must not revive UI or audio.');
console.log('Ocean timer: gradual fade, deadline recovery, cancellation, completion, and disposal passed.');
