/* Generated by build/generate-cms-artifacts.js. Do not edit directly. */
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) {
    module.exports = api;
  }
  if (root) {
    root.SITE_AUDIENCE_CONFIG = api;
    root.SITE_AUDIENCES = api.audiences;
    root.SITE_AUDIENCE_ORDER = api.order;
    root.SITE_AUDIENCE_DEFAULT = api.defaultAudience;
    root.getSiteAudienceConfig = api.getAudience;
    root.normalizeSiteAudience = api.normalizeAudience;
    root.detectSiteAudienceFromPath = api.detectAudienceFromPath;
  }
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  const audiences = {
    personal: {
      key: 'personal',
      label: 'Personal Site',
      shortLabel: 'Personal',
      homePath: '/',
      portfolioPath: '/portfolio',
      portfolioAllPath: '/portfolio',
      contactPath: '/contact',
      startHere: [
        {
          id: 'handwritingRating',
          label: 'Featured project',
          title: 'Handwriting Legibility Scoring',
          description: 'Try a handwriting demo and explore how confidently a model recognizes handwritten digits.',
          href: '/portfolio/handwritingRating',
          icon: 'pencil',
          accent: '#005fed',
          contentType: 'project',
          resourceType: 'case_study'
        },
        {
          id: 'tools',
          label: 'Useful tools',
          title: 'Practical Browser Tools',
          description: 'Open focused utilities for text, links, media, and repeatable browser workflows.',
          href: '/tools',
          icon: 'wrench',
          accent: '#087f8c',
          contentType: 'directory',
          resourceType: 'library'
        }
      ],
      featuredProjectIds: [
        'retailStore',
        'chatbotLora',
        'digitGenerator',
        'smartSentence',
        'website'
      ],
      portfolioTitle: 'Project Library',
      portfolioDescription: 'AI and analytics projects that explore real-world questions and solve everyday problems.',
      brandNavPrimary: 'Projects, Tools, and Games',
      brandTagline: 'Solving everyday problems with data and thoughtful tools.'
    }
  };

  const order = [
    'personal'
  ];
  const defaultAudience = 'personal';

  function normalizeAudience(value) {
    const raw = String(value || '').trim().toLowerCase();
    if (!raw) return defaultAudience;
    return audiences[raw] ? raw : defaultAudience;
  }

  function getAudience(value) {
    return audiences[normalizeAudience(value)] || audiences[defaultAudience];
  }

  function detectAudienceFromPath(pathname) {
    const path = String(pathname || '').trim().replace(/\/+$/, '') || '/';
    return order.find((key) => {
      const audience = audiences[key];
      if (!audience) return false;
      return path === audience.homePath;
    }) || null;
  }

  return {
    defaultAudience,
    order,
    audiences,
    normalizeAudience,
    getAudience,
    detectAudienceFromPath
  };
});
