/* Generated by build/generate-cms-artifacts.js. Do not edit directly. */
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) {
    module.exports = api;
  }
  if (root) {
    root.SITE_AUDIENCE_CONFIG = api;
    root.SITE_AUDIENCES = api.audiences;
    root.SITE_AUDIENCE_ORDER = api.order;
    root.SITE_AUDIENCE_DEFAULT = api.defaultAudience;
    root.getSiteAudienceConfig = api.getAudience;
    root.normalizeSiteAudience = api.normalizeAudience;
    root.detectSiteAudienceFromPath = api.detectAudienceFromPath;
  }
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  const audiences = {
    personal: {
      key: 'personal',
      label: 'Personal Site',
      shortLabel: 'Personal',
      homePath: '/',
      portfolioPath: '/portfolio',
      portfolioAllPath: '/portfolio',
      resumePath: '',
      resumePreviewPath: '',
      resumeDownloadPath: '',
      featuredProjectIds: [
        'retailStore',
        'chatbotLora',
        'digitGenerator',
        'smartSentence',
        'website'
      ],
      portfolioTitle: 'Project Library',
      portfolioDescription: 'A collection of data projects, software experiments, tools, and notes from Daniel Short.',
      resumeNavTitle: null,
      resumeNavSubtitle: null,
      resumePreviewSubtitle: null,
      resumeDownloadSubtitle: null,
      brandNavPrimary: 'Projects, Tools, and Notes'
    }
  };

  const order = [
    'personal'
  ];
  const defaultAudience = 'personal';

  function normalizeAudience(value) {
    const raw = String(value || '').trim().toLowerCase();
    if (!raw) return defaultAudience;
    if (raw === 'datascience' || raw === 'data_science') return 'data-science';
    if (raw === 'tourism-analytics') return 'tourism';
    return audiences[raw] ? raw : defaultAudience;
  }

  function getAudience(value) {
    return audiences[normalizeAudience(value)] || audiences[defaultAudience];
  }

  function detectAudienceFromPath(pathname) {
    const path = String(pathname || '').trim().replace(/\/+$/, '') || '/';
    return order.find((key) => {
      const audience = audiences[key];
      if (!audience) return false;
      return path === audience.homePath
        || path === audience.resumePath
        || path === audience.resumePreviewPath;
    }) || null;
  }

  return {
    defaultAudience,
    order,
    audiences,
    normalizeAudience,
    getAudience,
    detectAudienceFromPath
  };
});
